
version: '3.2'
services:
 db:
  image: mysql:5.7
  volumes:
   - type: volume
     source: db_data
     target: /var/lib/mysql

  ports:
   - "3306:3306"  

  restart: always
  environment:
   MYSQL_ROOT_PASSWORD: pswd
   MYSQL_DATABASE: games
   MYSQL_USER: username
   MYSQL_PASSWORD: password

 flask_server:
  image: wog_flask_server:latest 
  ports:
  - "8777:8777"
  environment:
   DB_CONNECTION: db:3306

volumes:
 db_data:
